# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mero
tagline: Pure, simple &amp; genuine.
description: >- # this means to ignore newlines until "baseurl:"
    A collection of points of view, opinions, suggestions and completely random thoughts by Pedro Pinto.
baseurl: "/blog" # the subpath of your site, e.g. /blog
timezone: PT
permalink: /:slug
url: https://pedropinto.me # the base hostname & protocol for your site, e.g. http://example.com
google_analytics_id: UA-13159742-2
color_scheme: prefers-dark

# Code snippets syntax highlight
highlighter: rouge

# Archives / Category pages
jekyll-archives:
    enabled: [categories]
    layout: category
    permalinks:
        category: "/category/:name/"

# Pagination
pagination:
    enabled: true
    per_page: 12
    title: ""
    permalink: "/page/:num/"
    trail:
        before: 2
        after: 2
    sort_field: "date"
    sort_reverse: true

# SEO Tag data
author:
    name: Pedro Pinto
    twitter: pmpinto
    website: https://pedropinto.me
    email: pedropinto.web@gmail.com
logo: /assets/images/open_graph.png
twitter:
    username: pmpinto
    card: summary_large_image
social:
    name: Pedro Pinto
    links:
        - https://github.com/pmpinto
        - https://twitter.com/pmpinto
        - https://dribbble.com/pmpinto
        - https://www.last.fm/user/xoldmanx
        - https://500px.com/pmpinto

# Default front matter
defaults:
    - scope:
          path: ""
      values:
          image:
              path: /assets/images/open_graph.png
              width: 1024
              height: 500

# Build settings
remote_theme: pmpinto/jekyll-mero
destination: dist
markdown: kramdown
plugins:
    - jekyll-paginate-v2
    - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - package.json
    - assets/javascript/*.es6.js
    - assets/javascript/index.js
    - webpack.config.js
