version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.1-node
        steps:
            - checkout
            - run:
                  name: Debug info
                  command: gem list bundler
            - run:
                  name: Update bundler
                  command: gem install bundler -v 2.0.2
            - run:
                  name: Check bundler version
                  command: bundler -v
            - run:
                  name: Install ruby dependencies
                  command: bundle
            - run:
                  name: Install npm dependencies
                  command: npm i
            - run:
                  name: Build
                  command: npm run build
