version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run:
                  name: Echo tests
                  command: echo "A first hello"
