version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.1-node
        steps:
            - checkout
            - run:
                  name: Update gems
                  command: sudo gem update --system
            - run:
                  name: Update bundler
                  command: gem install bundler
            - run:
                  name: Remove Gemfile.lock
                  command: rm Gemfile.lock
            - run:
                  name: Install ruby dependencies
                  command: bundle install
            - run:
                  name: Install npm dependencies
                  command: npm i
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Clone parent repo
                  command: git clone git@github.com:pmpinto/pmpinto.github.io.git
            - run:
                  name: Copy dist folder to new repo
                  command: mv ./dist ./pmpinto.github.io/blog
            - run:
                  name: Move into parent repo folder
                  command: cd ./pmpinto.github.io
            - run:
                  name: Deploy
                  command: |
                      git config user.email "circleci@pedropinto.me"
                      git config user.name "ci-builder"
                      git status
                      git add --all blog
                      git commit -m "Update blog with latest build"
                      git push
            # - persist_to_workspace:
            #     root: ./
            #     paths: dist
