version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run:
                  name: Install npm dependencies
                  command: npm i
            - run:
                  name: Install ruby dependencies
                  command: bundle
            - run:
                  name: Build
                  command: npm run build
