version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.4-node
        steps:
            - checkout
            - run:
                  name: Update gems
                  command: sudo gem update --system
            - run:
                  name: Update bundler
                  command: gem install bundler -v 2.0.2
            # - run:
            #       name: Remove Gemfile.lock
            #       command: rm Gemfile.lock
            - run:
                  name: Install ruby dependencies
                  command: bundle install
            - run:
                  name: Build jekyll
                  command: bundle exec jekyll build --trace
            - run:
                  name: Clone parent repo
                  command: git clone git@github.com:pmpinto/pmpinto.github.io.git
            - run:
                  name: Remove previous dist folder
                  command: rm -rf ./pmpinto.github.io/blog
            - run:
                  name: Copy dist folder to new repo
                  command: mv ./dist ./pmpinto.github.io/blog
            - run:
                  name: Deploy
                  command: |
                      commitId=$(git log -1 --pretty=%h)
                      commitMessage=$(git log -1 --pretty=%B)
                      cd pmpinto.github.io
                      ls
                      git config user.email "circleci@pedropinto.me"
                      git config user.name "ci-builder"
                      git add --all blog
                      git status
                      git commit -m "(Circle CI) ($commitId) $commitMessage"
                      git push origin master
