version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.1-node
        steps:
            - checkout
            - run:
                  name: Update gems
                  command: sudo gem update --system
            - run:
                  name: Update bundler
                  command: gem install bundler
            - run:
                  name: Remove Gemfile.lock
                  command: rm Gemfile.lock
            - run:
                  name: Install ruby dependencies
                  command: bundle install
            - run:
                  name: Install npm dependencies
                  command: npm i
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Deploy
                  command: ls && ls dist
